module SimpleCov
  module CLI
    module Watch
      module TestPlan
        def self?.build: (Array[String] changed, untyped document, root: String, input: String, stderr: untyped) -> Hash[Symbol, untyped]

        def self?.watched_paths: (untyped document, String root) -> Array[String]



        def self?.recorded_test_files: (untyped document) -> Array[String]
      end
    end
  end
end
