version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/test_projects/monorepo"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/test_projects/parallel_tests"
    schedule:
      interval: "weekly"
