module SimpleCov
  class Baseline
    CRITERIA: Hash[String, Symbol]

    HEADER: String

    module Parser
      def self?.call: (untyped data, String path) -> Hash[String, Hash[Symbol, Floor]]

      def self?.parse_entry: (untyped file, untyped entry, String path) -> Hash[Symbol, Floor]

      def self?.parse_criterion: (untyped file, untyped criterion_key, String path) -> Symbol

      def self?.parse_floor: (untyped file, untyped floor, String path) -> Floor
    end
  end
end
