module ActionView
  class Template
    def self.new: (String source, String identifier, untyped handler,
                   locals: Array[Symbol], ?format: Symbol?) -> Template

    def self.registered_template_handler: (String extension) -> untyped
  end
end
