# frozen_string_literal: true

source "https://rubygems.org"

gem "logger"
gem "rails", "~> 8.1"
gem "simplecov", path: "../../.."

gem "bigdecimal" if RUBY_VERSION >= "3.4"
gem "mutex_m" if RUBY_VERSION >= "3.4"
gem "drb" if RUBY_VERSION >= "3.4"
gem "benchmark" if RUBY_VERSION >= "4.0"
