module SimpleCov
  module CLI
    module Affected
      module ChangedFiles
        def self?.call: (String base, untyped stderr) -> Hash[Symbol, untyped]?

        def self?.toplevel: (untyped stderr) -> String?

        def self?.list: (String command, Array[String] argv, untyped stderr) -> Array[String]?

        def self?.report: (untyped stderr, String message) -> nil
      end
    end
  end
end
