# frozen_string_literal: true

module SimpleCov
  module CLI
    module Completions
      # The per-shell renderers. Each receives the same parsed usage data and
      # returns the complete script text. The completions command's own shell-name
      # argument is the one thing the usage tables don't carry, so each renderer
      # wires it in by hand.
      module Scripts
        extend self

        def fish(commands, options)
          lines = ["# Completions for simplecov. Generated by `simplecov completions fish`."] #: Array[String]
          commands.each do |name, desc|
            lines << "complete -c simplecov -f -n __fish_use_subcommand -a #{name} -d #{fish_quote(desc)}"
          end
          options.each { |name, list| list.each { |option| lines << fish_option(name, option) } }
          lines << "complete -c simplecov -f -n '__fish_seen_subcommand_from completions' -a 'fish bash zsh'"
          lines.join("\n")
        end

        def fish_option(name, option)
          parts = ["complete -c simplecov -n '__fish_seen_subcommand_from #{name}'"] #: Array[String]
          parts << "-s #{(_ = option.fetch(:short)).delete_prefix("-")}" if option.fetch(:short)
          parts << "-l #{option.fetch(:long).delete_prefix("--")}"
          parts << "-r" if option.fetch(:arg)
          parts << "-d #{fish_quote(option.fetch(:desc))}"
          parts.join(" ")
        end

        def fish_quote(text)
          "'#{text.gsub("\\") { "\\\\" }.gsub("'") { "\\'" }}'"
        end

        BASH_TAIL = [
          "  esac",
          '  [[ "$cur" == -* ]] && COMPREPLY=( $(compgen -W "$opts" -- "$cur") )',
          "}",
          "complete -o default -F _simplecov simplecov"
        ].freeze

        def bash(commands, options)
          (bash_head(commands) + bash_cases(options) + BASH_TAIL).join("\n")
        end

        def bash_head(commands)
          [
            "# Completions for simplecov. Generated by `simplecov completions bash`.",
            "_simplecov() {",
            '  local cur="${COMP_WORDS[COMP_CWORD]}" opts=""',
            '  if [ "$COMP_CWORD" -eq 1 ]; then',
            "    COMPREPLY=( $(compgen -W \"#{commands.collect(&:first).join(" ")}\" -- \"$cur\") ); return",
            "  fi",
            '  case "${COMP_WORDS[1]}" in'
          ]
        end

        def bash_cases(options)
          shells = '    completions) COMPREPLY=( $(compgen -W "fish bash zsh -h --help" -- "$cur") ); return;;'
          cases = [shells] #: Array[String]
          options.each do |name, list|
            next if name.eql?("completions")

            words = list.flat_map { |option| [option.fetch(:short), option.fetch(:long)] }.compact.join(" ")
            cases << "    #{name}) opts=\"#{words}\";;"
          end
          cases
        end

        ZSH_MIDDLE = [
          "  )",
          "  if (( CURRENT == 2 )); then",
          "    _describe -t commands 'simplecov command' commands",
          "    return",
          "  fi",
          '  case "$words[2]" in'
        ].freeze

        ZSH_TAIL = ["  esac", "}", '_simplecov "$@"'].freeze

        def zsh(commands, options)
          head = ["#compdef simplecov", "# Completions for simplecov. Generated by `simplecov completions zsh`.",
            "_simplecov() {", "  local -a commands", "  commands=("]
          rows = commands.collect { |name, desc| "    '#{name}:#{zsh_quote(desc)}'" }
          (head + rows + ZSH_MIDDLE + zsh_cases(options) + ZSH_TAIL).join("\n")
        end

        def zsh_cases(options)
          options.collect do |name, list|
            specs = +""
            specs << "'1:shell:(fish bash zsh)' " if name.eql?("completions")
            list.each { |option| zsh_specs(option).each { |spec| specs << spec << " " } }
            "    #{name}) _arguments #{specs.chop};;"
          end
        end

        # `'--input=[desc]'`: the `=` marks an argument-taking switch, which optparse
        # accepts in that spelling too. Brackets would end the description early, so
        # they are dropped from it.
        def zsh_specs(option)
          desc = "[#{zsh_quote(option.fetch(:desc).delete("[]"))}]"
          specs = [] #: Array[String]
          specs << "'#{option.fetch(:short)}#{desc}'" if option.fetch(:short)
          specs << "'#{option.fetch(:long)}#{"=" if option.fetch(:arg)}#{desc}'"
        end

        def zsh_quote(text)
          text.gsub("'") { "'\\''" }
        end
      end
    end
  end
end
