module SimpleCov
  module Formatter
    class JSONFormatter
      class ErrorsFormatter
        CRITERION_KEYS: Hash[Symbol, Symbol]

        def self.call: (untyped result) -> Hash[Symbol, Hash[untyped, untyped]]

        private

        def self.format_minimum_overall: (untyped result, Hash[Symbol, Hash[untyped, untyped]] errors) -> untyped

        def self.format_minimum_by_file: (untyped result, Hash[Symbol, Hash[untyped, untyped]] errors) -> untyped

        def self.format_baseline: (untyped result, Hash[Symbol, Hash[untyped, untyped]] errors) -> untyped

        def self.record_by_file: (untyped violation, Hash[Symbol, Hash[untyped, untyped]] errors) -> untyped

        def self.format_minimum_by_group: (untyped result, Hash[Symbol, Hash[untyped, untyped]] errors) -> untyped

        def self.format_maximum_overall: (untyped result, Hash[Symbol, Hash[untyped, untyped]] errors) -> untyped

        def self.format_maximum_drop: (untyped result, Hash[Symbol, Hash[untyped, untyped]] errors) -> untyped

        def self.format_maximum_missed: (untyped result, Hash[Symbol, Hash[untyped, untyped]] errors) -> untyped

        def self.format_maximum_missed_per_file: (untyped result, Hash[Symbol, Hash[untyped, untyped]] errors) -> untyped

        def self.maximum_actual: (untyped violation) -> { maximum: untyped, actual: untyped }

        def self.bucket: (Hash[Symbol, Hash[untyped, untyped]] errors, Symbol name) -> Hash[untyped, untyped]

        def self.key_for: (untyped violation) -> Symbol

        def self.expected_actual: (untyped violation) -> { expected: untyped, actual: untyped }
      end
    end
  end
end
