module SimpleCov
  module Formatter
    class JSONFormatter
      module ProductionSectionFormatter
        def self?.call: (?String? path) -> Hash[Symbol, untyped]?

        def self?.section: (Hash[String, untyped] store) -> Hash[Symbol, untyped]

        def self?.files: (Hash[String, untyped] store) -> Hash[String, Hash[Symbol, untyped]]
      end
    end
  end
end
