module SimpleCov
  module StaticCoverageExtractor
    module MethodCollector : ::Prism::Visitor
      @methods: Hash[untyped, Integer]
      @class_stack: Array[String]

      def visit_class_node: (Prism::ClassNode node) -> void

      def visit_module_node: (Prism::ModuleNode node) -> void

      def visit_def_node: (Prism::DefNode node) -> void

      private

      def constant_name: (untyped node) -> String

      def with_class: (String name) { () -> void } -> void
    end
  end
end
