module SimpleCov
  module StaticCoverageExtractor
    module PrismCompat
      IF_NODE_SUBSEQUENT_METHOD: untyped

      ELSE_CLAUSE_METHOD: untyped

      def self?.subsequent: (untyped node) -> untyped

      def self?.else_clause: (untyped node) -> untyped
    end
  end
end
