module SimpleCov
  module StaticCoverageExtractor
    module ValuePositions
      def self?.call: (untyped root) -> untyped

      def self?.mark: (untyped node, untyped in_value, untyped positions) -> untyped

      def self?.tail_children: (untyped node, untyped in_value) -> Array[untyped]
    end
  end
end
