module SimpleCov
  module StaticCoverageExtractor
    class Visitor < ::Prism::Visitor
      @branches: untyped

      @next_id: untyped

      include MethodCollector
      include LocationConventions
      include ConditionFolding

      attr_reader branches: untyped

      attr_reader methods: untyped

      def initialize: () -> void

      def visit_if_node: (untyped node) -> untyped

      def visit_unless_node: (untyped node) -> untyped

      def visit_call_node: (untyped node) -> untyped

      def visit_case_node: (untyped node) -> untyped

      def visit_case_match_node: (untyped node) -> untyped

      def visit_while_node: (untyped node) -> untyped

      def visit_until_node: (untyped node) -> untyped

      private

      def emit_if_like: (untyped node, untyped type) -> untyped

      def emit_safe_navigation: (untyped node) -> untyped

      def emit_case_like: (untyped node, untyped when_type) -> untyped

      def emit_loop: (untyped node, untyped type) -> untyped

      def build_tuple: (untyped type, untyped location) -> ::Array[untyped]
    end
  end
end
