module SimpleCov
  module CLI
    module CommandHelpers
      STATS_ROW_FORMAT: ::String

      class HelpRequested < StandardError
      end

      def name: () -> ::String

      def on_help: (untyped parser) -> untyped

      def build_parser: () ?{ (untyped parser) -> untyped } -> untyped

      def command_name: () -> ::String

      def quiet_option: (untyped parser, Hash[Symbol, untyped] opts) -> untyped

      def one?: (::Integer count) -> bool

      def error: (untyped stderr, untyped message) -> 1

      def error_nil: (untyped stderr, untyped message) -> nil

      def recorded_contexts: (untyped document, untyped opts, untyped stderr) -> Array[String]?

      def common_options: (untyped parser, untyped opts) -> untyped

      def parse_common: (untyped args, ?::Hash[Symbol, untyped] defaults) ?{ (untyped, untyped) -> untyped } -> [untyped, untyped]

      def stats_row: (untyped label, untyped percent_text, untyped covered, untyped total) -> ::String
    end
  end
end
