module SimpleCov
  module CLI
    module DeadCode
      include CommandHelpers

      extend CommandHelpers

      def self?.command_name: () -> String

      def self?.run: (untyped args, stdout: untyped, stderr: untyped, **untyped) -> (0 | 1)

      def self?.parse: (untyped args, untyped stderr) -> (untyped | nil)

      def self?.missing_production: (untyped stderr) -> nil

      def self?.load_production: (String path, untyped stderr) -> (Hash[String, untyped] | nil)

      def self?.cross: (untyped coverage, Hash[String, Array[Integer]] production_coverage) -> Hash[Symbol, untyped]

      def self?.classify_file: (Hash[Symbol, untyped] matrix, String file, Array[untyped] lines, Array[Integer] production_lines) -> void

      def self?.classify_line: (bool tested, bool in_production) -> Symbol?

      def self?.record: (Hash[Symbol, untyped] matrix, String file, Hash[Symbol, Array[Integer]] buckets, Integer relevant) -> void
    end
  end
end
