module SimpleCov
  module CLI
    module Dotfile
      def self?.coverage_dir: () -> untyped

      def self?.baseline_file: () -> String

      def self?.read_baseline_file_from: (untyped dotfile) -> String

      def self?.production_coverage: () -> String?

      def self?.read_production_coverage_from: (untyped dotfile) -> String?

      def self?.read_from: (untyped dotfile) -> untyped

      def self?.find: () -> (untyped | nil)

      def self?.with_simplecov_loaded: () { () -> untyped } -> untyped

      NEUTERED: Proc

      def self?.load_simplecov: () -> untyped

      def self?.load_with_start_neutered: (untyped path) -> untyped

      def self?.silence_verbose: () { () -> untyped } -> untyped
    end
  end
end
