module SimpleCov
  module CLI
    module Git
      def self?.capture: (*String argv) -> [String?, String, bool]

      def self?.toplevel: () -> String?

      def self?.option_like_ref?: (String ref) -> bool

      def self?.default_base: () -> String
    end
  end
end
