module SimpleCov
  module CLI
    module History
      include CommandHelpers

      extend CommandHelpers

      def self?.run: (untyped args, stdout: untyped, stderr: untyped, **untyped) -> (0 | 1)

      def self?.parse: (untyped args, untyped stderr) -> (untyped | nil)

      def self?.default_input: () -> String

      def self?.load_entries: (String path, untyped stderr) -> (Array[SimpleCov::History::entry] | nil)

      def self?.file_recorded?: (Array[SimpleCov::History::entry] entries, untyped opts, untyped stderr) -> bool
    end
  end
end
