module SimpleCov
  module CLI
    module Merge
      include CommandHelpers

      extend CommandHelpers

      def self?.run: (untyped args, stdout: untyped, stderr: untyped, **untyped) -> (untyped | 1 | 0)


      def self?.result_merger: () -> untyped


      def self?.commit: (untyped opts, untyped result, untyped stdout) -> untyped

      def self?.parse: (untyped args) -> untyped


      def self?.parse_inputs: (untyped files, untyped stderr) -> untyped

      def self?.parse_input: (untyped path, untyped stderr) -> untyped

      def self?.parse_input_error: (untyped stderr, untyped path, untyped reason) -> nil

      def self?.warn_about_duplicate_command_names: (untyped parsed, untyped stderr) -> untyped

      def self?.duplicate_warning: (untyped command_name, untyped paths) -> ::String

      def self?.write: (untyped path, untyped result) -> untyped

    end
  end
end
