module SimpleCov
  module CLI
    module Open
      include CommandHelpers

      extend CommandHelpers

      def self?.run: (untyped args, stderr: untyped, **untyped) -> untyped

      def self?.parse: (untyped args) -> untyped

      def self?.browser_opener: () -> untyped
    end
  end
end
