module SimpleCov
  module CLI
    module Patch
      include CommandHelpers

      extend CommandHelpers


      def self?.run: (untyped args, stdout: untyped, stderr: untyped, **untyped) -> (0 | 1)

      def self?.parse: (untyped args, untyped stderr) -> (untyped | nil)

      def self?.positional_ok?: (untyped rest, untyped stderr) -> bool

      def self?.compute_rows: (untyped coverage, ::Hash[::Symbol, untyped] diffed, untyped stderr) -> ::Array[untyped]

      def self?.changed_for: (untyped lines, untyped payload) -> ::Array[::Integer]

      def self?.warn_stale: (untyped path, untyped payload, ::Array[::Integer] changed, untyped stderr) -> void

      def self?.build_row: (untyped path, untyped payload, untyped changed) -> { file: untyped, line: untyped, branch: untyped, method: untyped }

      def self?.line_stats: (untyped hits, untyped changed) -> { covered: ::Integer, relevant: ::Integer, missing: ::Array[::Integer] }

      def self?.entry_stats: (untyped entries, untyped changed) -> ({ covered: ::Integer, relevant: ::Integer, missing: ::Array[::Integer] } | nil)

      def self?.each_touched: (untyped entries, untyped changed) { (::Integer, untyped) -> void } -> void

      def self?.scored?: (untyped row) -> bool
    end
  end
end
