module SimpleCov
  module CLI
    module Report
      include CommandHelpers

      extend CommandHelpers

      TOTAL_LABEL: ::String

      SECTIONS: ::Array[[::String, ::String]]

      def self?.run: (untyped args, stdout: untyped, stderr: untyped) -> (1 | 0)

      def self?.parse: (untyped args) -> untyped

      def self?.load_data: (untyped input, untyped stderr) -> (untyped | nil)

      def self?.emit_text: (untyped stdout, untyped data, untyped color) -> untyped

      def self?.emit_totals: (untyped stdout, untyped label, untyped totals, untyped color) -> untyped

      def self?.emit_section: (untyped stdout, untyped display, untyped section, untyped color) -> (nil | untyped)

      def self?.emit_json: (untyped stdout, untyped data) -> untyped

      def self?.collect_section: (untyped totals) -> untyped
    end
  end
end
