module SimpleCov
  module CLI
    module Run
      AUTOSTART: untyped

      def self?.run: (untyped args, stderr: untyped, **untyped) -> untyped

      def self?.exec_command: (untyped env, Array[String] cmd) -> untyped

      def self?.rubyopt_env: () -> untyped
    end
  end
end
