module SimpleCov
  module CLI
    module Serve
      include CommandHelpers

      extend CommandHelpers

      def self?.run: (untyped args, stdout: untyped, stderr: untyped, **untyped) -> untyped

      def self?.parse: (untyped args) -> untyped

      def self?.require_socket: () -> void

      def self?.announce: (untyped stdout, untyped server, untyped dir) -> untyped

      def self?.url_host: (String host) -> String

      def self?.with_server: (untyped opts, untyped stderr) { (TCPServer) -> untyped } -> untyped

      def self?.serve_loop: (untyped server, untyped dir, untyped stdout) -> untyped

    end
  end
end
