module SimpleCov
  module CLI
    module Show
      include CommandHelpers

      extend CommandHelpers

      def self?.run: (untyped args, stdout: untyped, stderr: untyped) -> Integer

      def self?.run_project: (untyped opts, untyped stdout, untyped stderr) -> Integer

      def self?.parse: (untyped args) -> untyped

      def self?.options: (untyped parser, untyped opts) -> untyped

      def self?.locate: (Hash[String, untyped] coverage, untyped opts, untyped stderr) -> [String, untyped]?

      def self?.render: ([String, untyped] located, untyped opts, untyped stdout, untyped stderr) -> Integer

      def self?.emit_json: (untyped entry, untyped opts, untyped stdout) -> Integer

      def self?.relevant_lines: (untyped entry) -> Array[Hash[Symbol, untyped]]

      def self?.show_uncovered: (untyped entry, untyped opts, untyped stdout, untyped stderr) -> Integer

      def self?.source_for: (String filename, untyped entry, untyped opts, untyped stderr) -> Array[String]?
    end
  end
end
