module SimpleCov
  module CLI
    module Usage
      def self?.text: (untyped cli) -> ::String

      def self?.for: (untyped cli, String command) -> ::String

      def self?.section_for?: (String section, String command) -> bool

      def self?.heading_of: (String section) -> String
    end
  end
end
