module SimpleCov
  module CLI
    module Diff
      module Output
        STATUS_SUFFIX: ::Hash[::String, ::String]

        def self?.emit_text: (untyped stdout, untyped rows, untyped color) -> untyped

        def self?.format_row: (untyped row, untyped color) -> untyped

        def self?.delta_parts: (untyped row, untyped color) -> untyped

        def self?.format_delta: (untyped delta, untyped label, untyped color) -> untyped
      end
    end
  end
end
