module SimpleCov
  class SourceFile
    class BranchBuilder
      @source_file: untyped

      def initialize: (untyped source_file) -> void

      def call: () -> untyped

      private

      def eval_generated_condition_to_ignore?: (untyped condition) -> (false | untyped)

      def build_branches_from: (untyped condition, untyped branches) -> untyped

      def build_branch: (untyped branch_data, untyped hit_count, untyped condition_range) -> (nil | untyped)

      def implicit_else_to_ignore?: (untyped type, untyped branch_range, untyped condition_range) -> (false | untyped)

      def process_skipped: (untyped branches) -> untyped
    end
  end
end
