module SimpleCov
  class SourceFile
    class LineBuilder
      @source_file: untyped

      def initialize: (untyped source_file) -> void

      def call: () -> untyped

      private

      def build_lines: () -> untyped

      def mark_skipped: (untyped lines, untyped chunks) -> untyped
    end
  end
end
