module SimpleCov
  class SourceFile
    class MethodBuilder
      @source_file: untyped

      def initialize: (untyped source_file) -> void

      def call: () -> untyped

      private

      def eval_generated_to_ignore?: (untyped info) -> (false | untyped)

      def process_skipped: (untyped methods) -> untyped
    end
  end
end
