module SimpleCov
  class SourceFile
    module RubyDataParser
      self.@parse_cache: Hash[String, untyped]?
      @parse_cache: Hash[String, untyped]?

      def self?.call: (untyped structure) -> untyped

      def self?.parse_cache: () -> Hash[String, untyped]

      def self?.parse_array_string: (untyped str) -> untyped

      def self?.parse_element: (untyped node) -> untyped

      def self?.const_path: (Array[untyped] node) -> String

      def self?.literal_text: (Array[untyped] node) -> untyped

      def self?.unescape_ruby: (untyped raw) -> untyped

      def self?.quote_inspected_class_segments: (untyped str) -> untyped
    end
  end
end
