module SimpleCov
  class SourceFile
    class SkipChunks
      self.@nocov_warned: untyped

      @filename: untyped

      @src: untyped

      @nocov_chunks: untyped

      @directive_chunks: untyped

      attr_reader self.nocov_warned: untyped

      def initialize: (untyped filename, untyped src) -> void

      def for: (untyped criterion) -> untyped

      def nocov_chunks: () -> untyped

      def directive_chunks: () -> untyped

      private

      def build_nocov_chunks: () -> untyped

      def warn_nocov_deprecation: (untyped first_line_number) -> (nil | untyped)
    end
  end
end
