module SimpleCov
  class SourceFile
    module SourceLoader
      SHEBANG_REGEX: ::Regexp

      RUBY_FILE_ENCODING_MAGIC_COMMENT_REGEX: ::Regexp

      def self?.call: (String filename) -> Array[String]

      def self?.open_file: [T] (String name, String mode) { (File file) -> T } -> T

      def self?.scrub_invalid: (String? line) -> String?

      def self?.shebang?: (untyped line) -> untyped

      def self?.read_lines: (untyped file, untyped lines, untyped current_line) -> untyped

      def self?.set_encoding_based_on_magic_comment: (untyped file, untyped line) -> (untyped | nil)

      def self?.ensure_remove_undefs: (untyped file_lines) -> untyped

      def self?.make_utf8: (String line) -> void
    end
  end
end
