module SimpleCov
  class TestTracker
    class ConstantWatch < Module
      @name: Symbol
      @on_added: (^() -> void)?

      def initialize: (Symbol name) { () -> void } -> void

      def attach: (Module host) -> self

      def notice: (Symbol added) -> void
    end
  end
end
