module SimpleCov
  module CLI
    module Serve
      module ReportPreparer
        def self.call: (String dir) -> String?

        def self.build_index: (String json_path, String dir) -> nil
      end
    end
  end
end
