module SimpleCov
  module CLI
    @coverage_dir: untyped

    interface _Command
      def run: (Array[String] args, stdout: IO, stderr: IO) -> Integer
    end

    COMMANDS: Hash[String, _Command]

    def self?.coverage_dir: () -> untyped

    def self?.default_input: () -> untyped

    def self?.color_enabled?: (untyped opts, untyped stream) -> (false | untyped)

    def self?.default_report: () -> untyped

    def self?.default_resultset: () -> untyped

    def self?.run: (untyped argv, ?stdout: untyped, ?stderr: untyped) -> (untyped | 1)

    def self?.dispatch: (_Command handler, untyped command, untyped rest, stdout: untyped, stderr: untyped) -> (untyped | 1)

    def self?.usage: () -> ::String
  end
end
