module SimpleCov
  module Color
    GREEN_THRESHOLD: 90

    YELLOW_THRESHOLD: 75

    ANSI: ::Hash[::Symbol, ::String]

    def self?.enabled?: (?untyped stream) -> (untyped | false | true)

    def self?.for_percent: (untyped percent) -> (:green | :yellow | :red)

    def self?.colorize: (untyped text, untyped color, ?enabled: untyped) -> (untyped | ::String)

    def self?.colorize_percent: (untyped percent, ?untyped? text, ?enabled: untyped) -> untyped

    def self?.env_set?: (untyped name) -> untyped
  end
end
