module SimpleCov
  module CommandGuesser
    attr_reader self.original_run_command: untyped

    def self.original_run_command=: (untyped command) -> untyped

    attr_writer self.original_program_name: untyped

    def self.original_program_name: () -> untyped

    def self.guess: () -> ::String

    private

    def self.parallel_data: () -> (nil | ::String)

    SEGMENT_START: ::Regexp

    SEGMENT_END: ::Regexp

    COMMAND_LINE_FRAMEWORKS: ::Hash[::Regexp, ::String]

    def self.from_command_line_options: () -> untyped

    EXECUTABLE_FRAMEWORKS: ::Hash[::String, ::String]

    def self.from_executable_name: () -> (nil | ::String)

    DEFINED_CONSTANT_FRAMEWORKS: ::Array[::Array["RSpec" | untyped] | ::Array["Unit Tests" | untyped] | ::Array["Minitest" | untyped] | ::Array["MiniTest" | untyped]]

    def self.from_defined_constants: () -> (untyped | "Unknown Test Framework")
  end
end
