module SimpleCov
  class CurrentRun
    @collating_result: bool?

    @forked_subprocess: bool?

    @subprocess_serial: Integer?

    attr_accessor pid: Integer?

    attr_accessor process_start_time: Time?

    attr_accessor result: Result?

    attr_writer collating_result: bool?

    def successor: () -> CurrentRun

    def result?: () -> (Result | false | nil)

    def collating_result?: () -> bool

    def forked_subprocess?: () -> bool

    def mark_forked_subprocess!: () -> void

    def subprocess_serial: () -> Integer

    def next_subprocess_serial!: () -> Integer

    attr_writer subprocess_serial: Integer?
  end
end
