module SimpleCov
  class Directive
    @line_number: untyped

    @mode: untyped

    @categories: untyped

    @inline: untyped

    CATEGORIES: ::Array[::Symbol]

    CATEGORY_PATTERN: ::String

    CATEGORIES_PATTERN: ::String

    PATTERN: ::Regexp

    attr_reader line_number: untyped

    attr_reader mode: untyped

    attr_reader categories: untyped

    def self.disabled_ranges: (untyped lines) -> untyped

    def self.directives_in: (untyped lines) -> (::Array[untyped] | untyped)

    def self.source_might_contain_directive?: (untyped lines) -> untyped

    def self.parse_comment: (untyped lines, untyped line_number, untyped column, untyped text) -> untyped

    def self.parse_categories: (untyped text) -> untyped

    def self.inline?: (untyped lines, untyped line_number, untyped column) -> untyped

    def self.comments_in: (untyped lines) -> untyped

    def initialize: (line_number: untyped, mode: untyped, categories: untyped, inline: untyped) -> void

    def disabled?: () -> untyped

    def inline?: () -> untyped

    def apply: (untyped ranges, untyped open_starts) -> untyped
  end
end
