
$ERROR_INFO: Exception?

module SimpleCov
  self.@exit_exception: untyped

  CoverageLimits: untyped

  def self.at_exit_behavior: () -> (nil | untyped)

  def self.run_exit_tasks: (?untyped error_exit_status) -> untyped

  def self.run_exit_tasks!: (?untyped error_exit_status) -> untyped

  def self.exit_status_from_exception: () -> (nil | untyped)

  def self.previous_error?: (untyped error_exit_status) -> untyped

  def self.report_previous_error: () -> (nil | untyped)

  def self.ready_to_process_results?: () -> untyped

  def self.report_processing_failure: (untyped exit_status) -> untyped

  def self.process_result: (untyped result) -> untyped

  def self.started_in_this_process?: () -> bool

  def self.successful?: (Integer status) -> bool

  def self.result_exit_status: (untyped result) -> untyped

  private

  def self.build_coverage_limits: () -> untyped
end
