module SimpleCov
  # Classifies whether lines are relevant for code coverage analysis.
  # Comments & whitespace lines, and :nocov: token blocks, are considered not relevant.
  class LinesClassifier
    RELEVANT: 0

    NOT_RELEVANT: nil

    WHITESPACE_LINE: ::Regexp

    COMMENT_LINE: ::Regexp

    WHITESPACE_OR_COMMENT_LINE: untyped

    def self.no_cov_line: () -> untyped

    def self.no_cov_line?: (untyped line) -> untyped

    def self.whitespace_line?: (untyped line) -> untyped

    def classify: (untyped lines) -> untyped

    private

    def not_relevant_line?: (untyped line, untyped line_number, untyped skipping, untyped directive_disabled) -> untyped

    def directive_disabled_line_set: (untyped lines) -> untyped
  end
end
