module SimpleCov
  class LinesClassifier
    RELEVANT: 0

    NOT_RELEVANT: nil

    WHITESPACE_LINE: ::Regexp

    COMMENT_LINE: ::Regexp

    WHITESPACE_OR_COMMENT_LINE: untyped

    def self.no_cov_line: () -> untyped

    def self.no_cov_line?: (untyped line) -> untyped

    def self.whitespace_line?: (untyped line) -> untyped

    def classify: (untyped lines) -> untyped

    private

    class SkipState
      @skipping: bool

      def initialize: () -> void

      def skipping?: () -> bool

      def toggle: () -> bool
    end

    def classify_line: (untyped line, untyped line_number, untyped directive_disabled, SkipState skip_state) -> untyped

    def directive_disabled_line_set: (untyped lines) -> untyped
  end
end
