module SimpleCov
  # Classifies whether lines are relevant for code coverage analysis.
  # Comments and whitespace lines, and lines inside a `# simplecov:disable`
  # block, are considered not relevant.
  class LinesClassifier
    RELEVANT: 0

    NOT_RELEVANT: nil

    WHITESPACE_LINE: ::Regexp

    COMMENT_LINE: ::Regexp

    WHITESPACE_OR_COMMENT_LINE: untyped

    def self.whitespace_line?: (untyped line) -> untyped

    def classify: (untyped lines) -> untyped

    private

    def classify_line: (untyped line, untyped line_number, untyped directive_disabled) -> untyped

    def directive_disabled_line_set: (untyped lines) -> untyped
  end
end
