module SimpleCov
  def self.defer_to_existing_report?: () -> (false | untyped)

  def self.existing_report_newer_than_us?: () -> (false | untyped)

  def self.warn_about_deferred_report: () -> (nil | untyped)
end
