module SimpleCov
  module SimulateCoverage
    def self?.call: (untyped absolute_path, ?synthesize: bool, ?lines: bool) -> Hash[String, untyped]

    def self?.synthesized_tuples: (untyped source_lines, bool synthesize) -> { "branches" => untyped, "methods" => untyped }

    def self?.read_lines: (untyped path) -> untyped

    def self?.coverage_stub: (untyped path, untyped source_lines) -> untyped
  end
end
