module SimpleCov
  module StaticCoverageExtractor
    def self?.call: (untyped source) -> untyped

    def self?.real_source_positions: (untyped source) -> (nil | { branches: untyped, methods: untyped })

    def self?.branch_start_line: (untyped, untyped, untyped, *untyped) -> untyped

    def self?.method_identity: (untyped, untyped, untyped, *untyped) -> Array[untyped]
  end
end
