module SimpleCov
  class TestTracker
    @delta: Delta
    @granularity: Symbol
    @segment: Segment?
    @lock: Mutex
    @owner: Thread?
    @depth: Integer
    @poisoned: bool

    self.@rspec_hook_installed: bool?

    class Segment < ::Struct[untyped]
      attr_accessor id: String
      attr_accessor opening: Hash[String, untyped]

      def self.new: (String id, Hash[String, untyped] opening) -> Segment
    end

    attr_reader map: ContextMap

    def initialize: (?root_regex: Regexp, ?granularity: Symbol) -> void

    def track: [T] (String test_id) { () -> T } -> T

    def poisoned?: () -> bool

    def recorded_map: (?closing: Hash[String, untyped]?) -> ContextMap?

    def self.install_framework_hooks: () -> void

    def self.install_rspec_hook: (?untyped rspec) -> void

    def self.rspec_module: () -> untyped

    def self.reset_rspec_hook!: () -> void

    def self.install_minitest_hook: (?untyped test_case) -> void

    def self.install_minitest_hook_when_loaded: (?Module root) -> void

    def self.watch_for_minitest_test: (untyped minitest) -> void

    def self.loaded_const: (Module mod, Symbol name) -> untyped

    def self.rspec_example_id: (untyped example) -> String

    def self.minitest_test_id: (untyped test) -> String

    def self.definition_site: (untyped test) -> Array[untyped]?

    module MinitestRun : ::Minitest::Test
      def run: () -> untyped
    end

    module Accessors : Configuration
      @test_tracker: TestTracker?

      def track_test: [T] (String test_id) { () -> T } -> T

      def test_tracker: () -> TestTracker?

      def start_test_tracking: () -> void
    end

    private

    def begin_track: (String id) -> Hash[String, untyped]?

    def note_entry: () -> bool

    def settle: (String id, Hash[String, untyped]? entry) -> void

    def open_segment: (String id) -> void

    def close_segment: (Hash[String, untyped] closing) -> void

    def flush_segment: (Hash[String, untyped]? closing) -> void

    def context_id: (String test_id) -> String

    def poison: () -> void
  end
end
