module SimpleCov
  module UnloadedFileInjector
    def self?.discover: (Array[String?] globs, root: String, ?reject: Array[Filter[untyped]]) -> Array[String]

    def self?.rejected?: (String path, Array[Filter[untyped]] filters) -> bool

    NO_COVERAGE_YET: Hash[String, Array[untyped]]

    def self?.call: (Hash[String, untyped] coverage, Array[String] paths, synthesize: bool, lines: bool) -> [Hash[String, untyped], Set[String]]
  end
end
