module SimpleCov
  module ViewCoverage
    def self?.compile_unrendered: () -> Array[String]

    def self?.enabled?: () -> bool

    def self?.discover: () -> Array[String]

    def self?.measured_paths: () -> Set[String]
  end
end
