module SimpleCov
  module ExitCodes
    class Check
      @result: untyped

      @thresholds: untyped

      @violations: untyped

      def initialize: (untyped result, untyped thresholds) -> void

      def failing?: () -> untyped

      def violations: () -> untyped

      def report: () -> untyped

      def report_lines: () -> Array[String]

      private

      attr_reader result: untyped

      attr_reader thresholds: untyped

      def compute_violations: () -> untyped

      def violation_lines: (untyped violation) -> Array[String]
    end
  end
end
