module SimpleCov
  module ExitCodes
    class MaximumMissedCheck < Check
      def exit_code: () -> untyped

      private

      def compute_violations: () -> untyped

      def violation_lines: (untyped violation) -> Array[String]
    end
  end
end
