module SimpleCov
  module CLI
    module Uncovered
      module Misses
        def self?.missed_for: (untyped payload, untyped criterion) -> ::Array[::Integer]

        def self?.collect: (untyped items) -> ::Array[::Integer]

        def self?.annotate: (untyped stdout, untyped files) -> untyped
      end
    end
  end
end
