@rspec @old_coverage_json @announce-output @announce-command

Feature:

  This test project has a resultset.json generated by simplecov 0.17.1 lying around
  (we changed the file format in 0.18) - as long as we want a hassle free upgrade
  path from 0.17 and below to our current version this cuke should pass :) #820

  Scenario: Running the tests succeeds
    When I open the coverage report generated with `bundle exec rspec spec`
    Then I should see the groups:
      | name      | coverage | files |
      | All Files | 80.0%    | 1     |
    And I should see a line coverage summary of 4/5
