# frozen_string_literal: true

module SimpleCov
  class SourceFile
    module BuilderContext
      def skip_chunks_for(criterion)
        (@skip_chunks ||= SkipChunks.new(filename, src)).chunks_for(criterion)
      end

      # Memoized set of real source positions extracted via Prism. Nil when Prism is
      # unavailable or parsing fails, signaling callers to keep every Coverage entry
      # rather than risk false drops. The `defined?` guard preserves a nil
      # memoization across calls.
      #
      # Nil for a template too, without parsing: every entry a template reports
      # is eval-generated by construction, so the filter has nothing to
      # distinguish there, and a template whose text happens to parse as Ruby
      # (a Haml `#id` tag reads as a comment) would otherwise lose its real
      # branches to a confident wrong parse.
      def real_source_positions
        return @real_source_positions if instance_variable_defined?(:@real_source_positions)
        return @real_source_positions = nil if Directive::Template.template?(filename)

        @real_source_positions = StaticCoverageExtractor.real_source_positions(src.join)
      end
    end
  end
end
