module SimpleCov
  module Combine
    module BranchesCombiner
      self.@identities: Hash[untyped, Integer]?
      @identities: Hash[untyped, Integer]?

      def self?.combine: (untyped coverage_a, untyped coverage_b) -> untyped

      def self?.absorb: (untyped target, untyped coverage) -> untyped

      def self?.materialize: (untyped target) -> untyped

      def self?.new_condition: (untyped condition) -> [untyped, Hash[untyped, untyped]]

      def self?.identities: () -> Hash[untyped, Integer]

      def self?.tuple_identity: (untyped tuple) -> ::Array[untyped]
    end
  end
end
