module SimpleCov
  module Combine
    module LinesCombiner
      def self?.merge_into: (untyped target, untyped source) -> untyped

      def self?.sum_into: (untyped target, untyped source, Integer size) -> untyped
    end
  end
end
