module SimpleCov
  class ContextMap
    class Union
      @map: ContextMap
      @complete: bool

      attr_reader carrying: Integer
      attr_reader entries: Integer

      def collector: () -> ^(Hash[String, untyped] surviving) -> void

      def absorb_resultset: (Hash[String, untyped] resultset) -> void

      def absorb_entry: (Hash[String, untyped] data) -> void

      def absorb_union: (Union other) -> self

      def complete?: () -> bool

      def map: () -> ContextMap?

      def partial_map: () -> ContextMap

      def warn_about_partial_maps: () -> nil
    end
  end
end
