name: stable

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      BUNDLE_WITHOUT: "benchmark"
      JRUBY_OPTS: "--debug"
    strategy:
      fail-fast: false

      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - '4.0'
          - jruby-9.4
          - jruby-10.0
          - truffleruby

    steps:
      - uses: actions/checkout@v6

      - run: rm Gemfile.lock

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: default
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rake rubocop
        # code style is enough to check once (and might even take some time on JRuby)
        if: matrix.ruby-version == '3.3'

      - name: Run tests
        run: bundle exec rake test
        if: "!contains(matrix.ruby-version, 'jruby') && matrix.ruby-version != 'truffleruby'"

      # Run only `rake spec` on truffleruby and jruby, because `rake` runs
      # cucumber which requires headless Chrome via cuprite/ferrum — this is
      # unreliable on alternative Ruby implementations.
      - name: Run specs (alternative implementations)
        run: bundle exec rake spec
        if: "contains(matrix.ruby-version, 'jruby') || matrix.ruby-version == 'truffleruby'"
